create table systems
(
    "id"                           integer,
    "edsm_id"                      integer,
    "name"                         text,
    "x"                            real,
    "y"                            real,
    "z"                            real,
    "population"                   integer,
    "is_populated"                 integer,
    "government_id"                integer,
    "government"                   text,
    "allegiance_id"                integer,
    "allegiance"                   text,
    "states"                       text,
    "security_id"                  integer,
    "security"                     text,
    "primary_economy_id"           integer,
    "primary_economy"              text,
    "power"                        text,
    "power_state"                  text,
    "power_state_id"               integer,
    "needs_permit"                 integer,
    "updated_at"                   integer,
    "minor_factions_updated_at"    integer,
    "simbad_ref"                   text,
    "controlling_minor_faction_id" integer,
    "controlling_minor_faction"    text,
    "reserve_type_id"              integer,
    "reserve_type"                 text,
    "ed_system_address"            integer
);

